// <auto-generated />
using System;
using DoAnCoSo_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnCoSo_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203065256_ThemBangDiemDanh")]
    partial class ThemBangDiemDanh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnCoSo_Web.Models.ChiTietGiangDay", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MaLopHoc");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("ChiTietGiangDay");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ChiTietHocTap", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<int?>("DiemTongKet")
                        .HasColumnType("int");

                    b.Property<string>("NhanXetCuaGiaoVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "MaLopHoc");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("ChiTietHocTap");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ChuyenNganh", b =>
                {
                    b.Property<int>("MaChuyenNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenNganh"));

                    b.Property<string>("TenChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaChuyenNganh");

                    b.ToTable("ChuyenNganh");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<int>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungDanhGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSaoDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("UserUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("UserUserId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DanhSachQuanTam", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MaKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("DanhSachQuanTam");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DiemDanh", b =>
                {
                    b.Property<int>("MaDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiemDanh"));

                    b.Property<bool>("CoMat")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaLopHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDiemDanh")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDiemDanh");

                    b.HasIndex("MaLopHoc");

                    b.HasIndex("UserId");

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.HinhAnhKhoaHoc", b =>
                {
                    b.Property<int>("MaHinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinh"));

                    b.Property<int>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<bool>("LaAnhDaiDien")
                        .HasColumnType("bit");

                    b.Property<byte[]>("NoiDungHinh")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("MaHinh");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.ToTable("HinhAnhKhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoaDon"));

                    b.Property<DateTime?>("NgayDongLan2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TienDongLan1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TienDongLan2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("UserUserId");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("GioBatDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioKetThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLopHoc"));

                    b.Property<int>("KhoaHocMaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKhaiGiang")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongHocMaPhongHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLopHoc");

                    b.HasIndex("KhoaHocMaKhoaHoc");

                    b.HasIndex("PhongHocMaPhongHoc");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.PhieuDangKyKhoaHoc", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThaiDangKy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "MaKhoaHoc", "MaHoaDon");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("PhieuDangKyKhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.PhongHoc", b =>
                {
                    b.Property<int>("MaPhongHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhongHoc"));

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongHoc");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.TinTucTuyenDung", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<byte[]>("HinhTinTuc")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTinTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeTinTuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuc");

                    b.ToTable("TinTucTuyenDung");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ToCaoDanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("MaDanhGia", "UserId")
                        .IsUnique();

                    b.ToTable("ToCaoDanhGia");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ChuyenNganhMaChuyenNganh")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMainAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime>("NgayDK")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenNganhMaChuyenNganh");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ChiTietGiangDay", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.LopHoc", "LopHoc")
                        .WithMany("ChiTietGiangDay")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany("ChiTietGiangDay")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ChiTietHocTap", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.LopHoc", "LopHoc")
                        .WithMany("ChiTietHocTap")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany("ChiTietHocTap")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DanhGia", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocMaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DanhSachQuanTam", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("DanhSachQuanTam")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany("DanhSachQuanTam")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DiemDanh", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.HinhAnhKhoaHoc", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("HinhAnhKhoaHoc")
                        .HasForeignKey("KhoaHocMaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.HoaDon", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.LopHoc", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocMaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("PhongHocMaPhongHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.PhieuDangKyKhoaHoc", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.HoaDon", "HoaDon")
                        .WithMany("PhieuDangKyKhoaHoc")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("PhieuDangKyKhoaHoc")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany("PhieuDangKyKhoaHoc")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("KhoaHoc");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.ToCaoDanhGia", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.DanhGia", "DanhGia")
                        .WithMany("ToCaoDanhGia")
                        .HasForeignKey("MaDanhGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", "User")
                        .WithMany("ToCaoDanhGia")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.User", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany()
                        .HasForeignKey("ChuyenNganhMaChuyenNganh");

                    b.Navigation("ChuyenNganh");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnCoSo_Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DoAnCoSo_Web.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.DanhGia", b =>
                {
                    b.Navigation("ToCaoDanhGia");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.HoaDon", b =>
                {
                    b.Navigation("PhieuDangKyKhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.KhoaHoc", b =>
                {
                    b.Navigation("DanhSachQuanTam");

                    b.Navigation("HinhAnhKhoaHoc");

                    b.Navigation("PhieuDangKyKhoaHoc");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.LopHoc", b =>
                {
                    b.Navigation("ChiTietGiangDay");

                    b.Navigation("ChiTietHocTap");
                });

            modelBuilder.Entity("DoAnCoSo_Web.Models.User", b =>
                {
                    b.Navigation("ChiTietGiangDay");

                    b.Navigation("ChiTietHocTap");

                    b.Navigation("DanhSachQuanTam");

                    b.Navigation("PhieuDangKyKhoaHoc");

                    b.Navigation("ToCaoDanhGia");
                });
#pragma warning restore 612, 618
        }
    }
}
